"""Held-out lipid blocks at requested distances from training -- generated.

Written by analysis/lipid_block_search.py; do not edit by hand. Each entry is a
set of lipid species (FullIdentityOfLipid) whose rows leave training for every
protein, exactly as a --lipid_coldsplit class set does, chosen so that the
block's isolation -- the mean over its structures of the best Tanimoto
similarity to a structure still in training -- lands on the requested value.

A bare key (0.85) is a global block, chosen against the whole table: any
protein may train on the chemistry left behind. A <family>__<value> key
(cral-trio__0.85) is scoped to one --family_only run: chosen so that
training on THAT family's own remaining rows alone reaches the requested
isolation, which a global block does not promise once every other family's
chemistry is unavailable.

The key is the REQUESTED isolation and the value --lipid_isolation takes;
BLOCK_GEOMETRY below records what each block actually measures, which is what
belongs on a plot -- and a run measures it again for itself anyway
(analysis/split_similarity_vs_metric.py rebuilds every run's own split).

This file accumulates across separate `--emit_module` calls (see
load_existing_module): each call below regenerated or added the keys it names,
not necessarily every key present.

    python3 analysis/lipid_block_search.py --granularity species --targets 0.55,0.554,0.546 --min_positives 40 --max_positives 140 --emit_module /home/kalinina/ltp/DL_project/dataloader/lipid_isolation_blocks.py
"""

LIPID_ISOLATION_BLOCKS = {
    "0.40": (
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
    ),
    "0.50": (
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Lysophosphatidylglycerol (16:1)",
        "Lysophosphatidylglycerol (17:1)",
        "Lysophosphatidylglycerol (18:1)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
    ),
    "0.546": (
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Diacylglycerol (32:1)",
        "Diacylglycerol (34:2)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Lysophosphatidylglycerol (16:1)",
        "Lysophosphatidylglycerol (17:1)",
        "Lysophosphatidylglycerol (18:1)",
        "Lysophosphatidylglycerol (19:1)",
        "Phosphatidylglycerol (36:1)",
        "Phosphatidylinositol (34:1)",
        "Phosphatidylinositol (36:1)",
        "Phosphatidylinositol (36:2)",
        "Phosphatidylinositol (38:2)",
        "Phosphatidylinositol (38:3)",
        "Phosphatidylinositol (38:4)",
        "Phosphatidylinositol (38:5)",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
        "Triacylglycerol (46:3)",
        "Triacylglycerol (47:2)",
        "Triacylglycerol (48:3)",
        "Triacylglycerol (50:2)",
        "Triacylglycerol (53:2)",
        "Triacylglycerol (54:2)",
    ),
    "0.55": (
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
    ),
    "0.554": (
        "Triacylglycerol (54:2)",
        "Triacylglycerol (56:5)",
        "docosapentaenoate",
        "docosatetraenoate",
        "docosatrienoate",
        "eicosapentaenoate",
        "eicosatetraenoate",
        "eicosatrienoate",
        "heptadecenoate",
        "hexadecenoate",
        "nonadecenoate",
        "octadecadienoate",
        "octadecatrienoate",
        "octadecatrienol",
        "octadecenoate",
    ),
    "0.596": (
        "Triacylglycerol (50:2)",
        "Triacylglycerol (53:2)",
        "Triacylglycerol (54:2)",
        "docosapentaenoate",
        "docosatetraenoate",
        "docosatrienoate",
        "eicosapentaenoate",
        "eicosatetraenoate",
        "eicosatrienoate",
        "heptadecenoate",
        "hexadecenoate",
        "nonadecenoate",
        "octadecadienoate",
        "octadecatrienoate",
        "octadecatrienol",
        "octadecenoate",
    ),
    "0.60": (
        "Ceramide (d36:1)",
        "Ceramide phosphate (d*34:1)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
    ),
    "0.600": (
        "Bismonoacylglycerolphosphate (36:2);Phosphatidylglycerol (36:2)",
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Diacylglycerol (32:1)",
        "Diacylglycerol (34:2)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Lysophosphatidylglycerol (16:1)",
        "Lysophosphatidylglycerol (17:1)",
        "Lysophosphatidylglycerol (18:1)",
        "Lysophosphatidylglycerol (19:1)",
        "Phosphatidylglycerol (36:1)",
        "Phosphatidylglycerol (36:2)",
        "Phosphatidylglycerol (37:1)",
        "Phosphatidylglycerol (37:2)",
        "Phosphatidylglycerol (38:2)",
        "Phosphatidylinositol (34:1)",
        "Phosphatidylinositol (36:1)",
        "Phosphatidylinositol (36:2)",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
        "Triacylglycerol (46:3)",
        "Triacylglycerol (47:2)",
        "Triacylglycerol (48:3)",
        "Triacylglycerol (50:2)",
        "Triacylglycerol (53:2)",
        "Triacylglycerol (54:2)",
    ),
    "0.70": (
        "Bismonoacylglycerolphosphate (36:2)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide phosphate (d*42:2)",
        "Diacylglycerol (32:1)",
        "Diacylglycerol (34:2)",
        "Lysophosphatidylglycerol (17:1)",
        "Lysophosphatidylglycerol (18:1)",
        "Lysophosphatidylglycerol (19:1)",
        "Phosphatidate (30:1)",
        "Phosphatidate (32:1)",
        "Phosphatidate (32:2)",
        "Phosphatidate (33:1)",
        "Phosphatidate (33:2)",
        "Phosphatidate (34:1)",
        "Phosphatidate (34:2)",
        "Phosphatidate (35:1)",
        "Phosphatidate (35:2)",
        "Phosphatidate (36:2)",
        "Phosphatidate (37:2)",
        "Triacylglycerol (46:3)",
        "Triacylglycerol (47:2)",
        "Triacylglycerol (48:3)",
        "Triacylglycerol (50:2)",
        "Triacylglycerol (53:2)",
        "Triacylglycerol (54:2)",
        "Triacylglycerol (56:5)",
        "docosapentaenoate",
        "docosatetraenoate",
        "docosatrienoate",
        "eicosapentaenoate",
        "eicosatetraenoate",
        "eicosatrienoate",
        "heptadecenoate",
        "hexadecenoate",
        "nonadecenoate",
        "octadecadienoate",
        "octadecatrienoate",
        "octadecatrienol",
        "octadecenoate",
    ),
    "0.80": (
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Diacylglycerol (32:1)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Triacylglycerol (32:0)",
        "heptadecenoate",
        "hexadecenoate",
        "nonadecenoate",
    ),
    "0.85": (
        "Phosphatidylethanolamine (28:1)",
        "Phosphatidylethanolamine (30:1)",
        "Phosphatidylethanolamine (30:2)",
        "Phosphatidylethanolamine (31:1)",
        "Phosphatidylethanolamine (32:1)",
        "Phosphatidylethanolamine (32:2)",
        "Phosphatidylethanolamine (33:1)",
        "Phosphatidylethanolamine (33:2)",
        "Phosphatidylethanolamine (34:1)",
        "Phosphatidylethanolamine (34:2)",
        "Phosphatidylethanolamine (34:3)",
        "Phosphatidylethanolamine (35:1)",
        "Phosphatidylethanolamine (35:2)",
        "Phosphatidylethanolamine (36:1)",
        "Phosphatidylethanolamine (36:2)",
        "Phosphatidylethanolamine (36:3)",
        "Phosphatidylethanolamine (37:2)",
        "Phosphatidylethanolamine (38:2)",
        "Phosphatidylethanolamine (38:4)",
        "Phosphatidylethanolamine (O-38:6)",
        "Phosphatidylethanolamine (O-40:8)",
    ),
    "0.90": (
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*34:2)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*42:3)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Lysophosphatidylcholine (18:2)",
        "Lysophosphatidylglycerol (16:1)",
        "Lysophosphatidylglycerol (17:1)",
        "Lysophosphatidylglycerol (18:1)",
        "Lysophosphatidylglycerol (19:1)",
        "Phosphatidylcholine (34:2)",
        "Phosphatidylcholine (34:4)",
        "Phosphatidylcholine (36:2)",
        "Phosphatidylcholine (36:4)",
        "Phosphatidylcholine (O-38:7)",
        "Phosphatidylcholine (O-40:7)",
        "Phosphatidylglycerophosphate (34:2)",
        "Phosphatidylglycerophosphate (36:2)",
        "Retinol",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (t*34:2)",
    ),
    "0.95": (
        "Lysophosphatidylcholine (36:4);Phosphatidylcholine (O-36:4)",
        "Lysophosphatidylcholine (38:5); Phosphatidylcholine (O-38:5)",
        "Phosphatidylcholine (34:4)",
        "Phosphatidylcholine (35:4)",
        "Phosphatidylcholine (38:6)",
        "Phosphatidylcholine (38:7)",
        "Phosphatidylcholine (39:5)",
        "Phosphatidylcholine (39:6)",
        "Phosphatidylcholine (40:4)",
        "Phosphatidylcholine (40:5)",
        "Phosphatidylcholine (40:7)",
        "Phosphatidylcholine (40:8)",
        "Phosphatidylcholine (42:10)",
        "Phosphatidylcholine (42:8)",
        "Phosphatidylcholine (O-32:1)",
        "Phosphatidylcholine (O-32:2)",
        "Phosphatidylcholine (O-32:3)",
        "Phosphatidylcholine (O-33:3)",
        "Phosphatidylcholine (O-34:1)",
        "Phosphatidylcholine (O-34:2)",
        "Phosphatidylcholine (O-34:3)",
        "Phosphatidylcholine (O-36:1)",
        "Phosphatidylcholine (O-36:2)",
        "Phosphatidylcholine (O-36:3)",
        "Phosphatidylcholine (O-36:5)",
        "Phosphatidylcholine (O-36:5); Lysophosphatidylcholine (36:5)",
        "Phosphatidylcholine (O-36:6);Lysophosphatidylcholine (36:6)",
        "Phosphatidylcholine (O-37:6)",
        "Phosphatidylcholine (O-38:3)",
        "Phosphatidylcholine (O-38:6)",
        "Phosphatidylcholine (O-38:7)",
        "Phosphatidylcholine (O-40:6)",
        "Phosphatidylcholine (O-40:7)",
    ),
    "cral-trio__0.56": (
        "Ceramide (DH46:0)",
        "Ceramide (DH48:0)",
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide (t46:0); Ceramide (DH46:0-OH)",
        "Ceramide (t48:0)",
        "Ceramide (t48:0); Ceramide (DH48:0-OH)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Diacylglycerol (32:1)",
        "Diacylglycerol (34:2)",
        "Dihexosyl ceramide (t*40:2)",
        "Dihexosyl ceramide (t*42:2)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d*42:3)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t*41:2)",
        "Hexosyl ceramide (t*42:3)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Lysophosphatidylglycerol (16:1)",
        "Lysophosphatidylglycerol (17:1)",
        "Lysophosphatidylglycerol (18:1)",
        "Lysophosphatidylglycerol (19:1)",
        "Phosphatidylglycerol (28:1)",
        "Phosphatidylglycerol (28:1);Bismonoacylglycerolphosphate (28:1)",
        "Phosphatidylglycerol (29:1)",
        "Phosphatidylglycerol (29:1);Bismonoacylglycerolphosphate (29:1)",
        "Phosphatidylglycerol (34:2);Bismonoacylglycerolphosphate (34:2)",
        "Phosphatidylinositol (34:1)",
        "Phosphatidylinositol (36:1)",
        "Phosphatidylinositol (36:2)",
        "Phosphatidylinositol (38:2)",
        "Phosphatidylinositol (38:3)",
        "Phosphatidylinositol (38:4)",
        "Phosphatidylinositol (38:5)",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
        "Sulfohexosyl ceramide (d42:1);Sulfohexosyl ceramide (DH42:1)",
        "Sulfohexosyl ceramide (d42:2);Sulfohexosyl ceramide (DH42:2)",
        "Triacylglycerol (46:3)",
        "Triacylglycerol (47:2)",
        "Triacylglycerol (48:3)",
        "Triacylglycerol (50:2)",
        "Triacylglycerol (53:2)",
        "Triacylglycerol (54:2)",
    ),
    "cral-trio__0.65": (
        "Ceramide (d*32:1)",
        "Ceramide (d*33:1)",
        "Ceramide (d*34:1)",
        "Ceramide (d*34:2)",
        "Ceramide (d32:1)",
        "Ceramide (d33:1)",
        "Ceramide (d34:1)",
        "Ceramide (d34:2)",
        "Ceramide (d36:1)",
        "Ceramide phosphate (d*32:1)",
        "Ceramide phosphate (d*32:2)",
        "Ceramide phosphate (d*33:1)",
        "Ceramide phosphate (d*34:1)",
        "Ceramide phosphate (d*34:2)",
        "Ceramide phosphate (d*36:1)",
        "Ceramide phosphate (d*36:2)",
        "Ceramide phosphate (d*40:1)",
        "Ceramide phosphate (d*42:2)",
        "Ceramide phosphate (d*42:3)",
        "Hexosyl ceramide (d*34:1)",
        "Hexosyl ceramide (d*36:1)",
        "Hexosyl ceramide (d*36:2)",
        "Hexosyl ceramide (d*40:1)",
        "Hexosyl ceramide (d*40:2)",
        "Hexosyl ceramide (d*41:1)",
        "Hexosyl ceramide (d42:1)",
        "Hexosyl ceramide (d42:2)",
        "Hexosyl ceramide (t*34:1)",
        "Hexosyl ceramide (t*34:2)",
        "Hexosyl ceramide (t*36:2)",
        "Hexosyl ceramide (t*41:1)",
        "Hexosyl ceramide (t40:1);Hexosyl ceramide (d40:1-OH)",
        "Hexosyl ceramide (t40:2);Hexosyl ceramide (d40:2-OH)",
        "Hexosyl ceramide (t42:1);Hexosyl ceramide (d42:1-OH)",
        "Hexosyl ceramide (t42:2);Hexosyl ceramide (d42:2-OH)",
        "Hexosyl ceramide (t44:2);Hexosyl ceramide (d44:2-OH)",
        "Lysophosphatidylcholine (18:0)",
        "Lysophosphatidylcholine (18:1)",
        "Lysophosphatidylcholine (18:1);Phosphatidylcholine (O-18:1)",
        "Lysophosphatidylcholine (18:2)",
        "Lysophosphatidylcholine (20:3);Phosphatidylcholine (O-20:3)",
        "Lysophosphatidylcholine (20:4)",
        "Lysophosphatidylcholine (22:5)",
        "Lysophosphatidylcholine (30:0); Phosphatidylcholine (O-30:0)",
        "Lysophosphatidylcholine (34:5);Phosphatidylcholine (O-34:5)",
        "Lysophosphatidylcholine (36:4);Phosphatidylcholine (O-36:4)",
        "Lysophosphatidylcholine (38:5); Phosphatidylcholine (O-38:5)",
        "Phosphatidylcholine (17:1)",
        "Phosphatidylcholine (19:1)",
        "Phosphatidylcholine (30:0)",
        "Phosphatidylcholine (30:1)",
        "Phosphatidylcholine (30:2)",
        "Phosphatidylcholine (31:0)",
        "Phosphatidylcholine (31:1)",
        "Phosphatidylcholine (32:0)",
        "Phosphatidylcholine (32:1)",
        "Phosphatidylcholine (32:2)",
        "Phosphatidylcholine (33:1)",
        "Phosphatidylcholine (33:2)",
        "Phosphatidylcholine (34:0)",
        "Phosphatidylcholine (34:1)",
        "Phosphatidylcholine (34:2)",
        "Phosphatidylcholine (34:3)",
        "Phosphatidylcholine (34:4)",
        "Phosphatidylcholine (35:1)",
        "Phosphatidylcholine (35:2)",
        "Phosphatidylcholine (35:4)",
        "Phosphatidylcholine (36:1)",
        "Phosphatidylcholine (36:2)",
        "Phosphatidylcholine (36:3)",
        "Phosphatidylcholine (36:4)",
        "Phosphatidylcholine (36:5)",
        "Phosphatidylcholine (36:6)",
        "Phosphatidylcholine (37:4)",
        "Phosphatidylcholine (37:5)",
        "Phosphatidylcholine (38:2)",
        "Phosphatidylcholine (38:3)",
        "Phosphatidylcholine (38:4)",
        "Phosphatidylcholine (38:5)",
        "Phosphatidylcholine (38:6)",
        "Phosphatidylcholine (38:7)",
        "Phosphatidylcholine (39:4)",
        "Phosphatidylcholine (39:5)",
        "Phosphatidylcholine (39:6)",
        "Phosphatidylcholine (40:2)",
        "Phosphatidylcholine (40:4)",
        "Phosphatidylcholine (40:5)",
        "Phosphatidylcholine (40:6)",
        "Phosphatidylcholine (40:7)",
        "Phosphatidylcholine (40:8)",
        "Phosphatidylcholine (42:10)",
        "Phosphatidylcholine (42:8)",
        "Phosphatidylcholine (O-32:0)",
        "Phosphatidylcholine (O-32:1)",
        "Phosphatidylcholine (O-32:2)",
        "Phosphatidylcholine (O-32:3)",
        "Phosphatidylcholine (O-33:3)",
        "Phosphatidylcholine (O-34:1)",
        "Phosphatidylcholine (O-34:2)",
        "Phosphatidylcholine (O-34:3)",
        "Phosphatidylcholine (O-34:4);Lysophosphatidylcholine (34:4)",
        "Phosphatidylcholine (O-35:5)",
        "Phosphatidylcholine (O-36:1)",
        "Phosphatidylcholine (O-36:2)",
        "Phosphatidylcholine (O-36:3)",
        "Phosphatidylcholine (O-36:5)",
        "Phosphatidylcholine (O-36:5); Lysophosphatidylcholine (36:5)",
        "Phosphatidylcholine (O-36:6);Lysophosphatidylcholine (36:6)",
        "Phosphatidylcholine (O-37:4)",
        "Phosphatidylcholine (O-37:6)",
        "Phosphatidylcholine (O-37:7)",
        "Phosphatidylcholine (O-38:3)",
        "Phosphatidylcholine (O-38:6)",
        "Phosphatidylcholine (O-38:7)",
        "Phosphatidylcholine (O-40:6)",
        "Phosphatidylcholine (O-40:7)",
        "Sphingomyelin (DH34:0)",
        "Sphingomyelin (d*32:1)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d35:1);Sphingomyelin (DH35:1)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d38:1);Sphingomyelin (DH38:1)",
        "Sphingomyelin (d39:1);Sphingomyelin (DH39:1)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
        "Sphingomyelin (t*34:2)",
    ),
    "cral-trio__0.70": (
        "Lysophosphatidylcholine (18:0)",
        "Lysophosphatidylcholine (18:1)",
        "Lysophosphatidylcholine (18:1);Phosphatidylcholine (O-18:1)",
        "Lysophosphatidylcholine (18:2)",
        "Lysophosphatidylcholine (20:3);Phosphatidylcholine (O-20:3)",
        "Lysophosphatidylcholine (20:4)",
        "Lysophosphatidylcholine (30:0); Phosphatidylcholine (O-30:0)",
        "Lysophosphatidylcholine (34:5);Phosphatidylcholine (O-34:5)",
        "Lysophosphatidylcholine (36:4);Phosphatidylcholine (O-36:4)",
        "Lysophosphatidylcholine (38:5); Phosphatidylcholine (O-38:5)",
        "Phosphatidylcholine (17:1)",
        "Phosphatidylcholine (19:1)",
        "Phosphatidylcholine (30:0)",
        "Phosphatidylcholine (30:1)",
        "Phosphatidylcholine (30:2)",
        "Phosphatidylcholine (31:0)",
        "Phosphatidylcholine (31:1)",
        "Phosphatidylcholine (32:0)",
        "Phosphatidylcholine (32:1)",
        "Phosphatidylcholine (32:2)",
        "Phosphatidylcholine (33:1)",
        "Phosphatidylcholine (33:2)",
        "Phosphatidylcholine (34:0)",
        "Phosphatidylcholine (34:1)",
        "Phosphatidylcholine (34:2)",
        "Phosphatidylcholine (34:3)",
        "Phosphatidylcholine (34:4)",
        "Phosphatidylcholine (35:1)",
        "Phosphatidylcholine (35:2)",
        "Phosphatidylcholine (35:4)",
        "Phosphatidylcholine (36:1)",
        "Phosphatidylcholine (36:2)",
        "Phosphatidylcholine (36:3)",
        "Phosphatidylcholine (36:4)",
        "Phosphatidylcholine (36:5)",
        "Phosphatidylcholine (36:6)",
        "Phosphatidylcholine (37:4)",
        "Phosphatidylcholine (37:5)",
        "Phosphatidylcholine (38:2)",
        "Phosphatidylcholine (38:3)",
        "Phosphatidylcholine (38:4)",
        "Phosphatidylcholine (38:5)",
        "Phosphatidylcholine (38:6)",
        "Phosphatidylcholine (38:7)",
        "Phosphatidylcholine (39:4)",
        "Phosphatidylcholine (39:5)",
        "Phosphatidylcholine (39:6)",
        "Phosphatidylcholine (40:2)",
        "Phosphatidylcholine (40:4)",
        "Phosphatidylcholine (40:5)",
        "Phosphatidylcholine (40:6)",
        "Phosphatidylcholine (40:7)",
        "Phosphatidylcholine (40:8)",
        "Phosphatidylcholine (42:10)",
        "Phosphatidylcholine (42:8)",
        "Phosphatidylcholine (O-32:0)",
        "Phosphatidylcholine (O-32:1)",
        "Phosphatidylcholine (O-32:2)",
        "Phosphatidylcholine (O-32:3)",
        "Phosphatidylcholine (O-33:3)",
        "Phosphatidylcholine (O-34:1)",
        "Phosphatidylcholine (O-34:2)",
        "Phosphatidylcholine (O-34:3)",
        "Phosphatidylcholine (O-34:4);Lysophosphatidylcholine (34:4)",
        "Phosphatidylcholine (O-35:5)",
        "Phosphatidylcholine (O-36:1)",
        "Phosphatidylcholine (O-36:2)",
        "Phosphatidylcholine (O-36:3)",
        "Phosphatidylcholine (O-36:5)",
        "Phosphatidylcholine (O-36:5); Lysophosphatidylcholine (36:5)",
        "Phosphatidylcholine (O-36:6);Lysophosphatidylcholine (36:6)",
        "Phosphatidylcholine (O-37:4)",
        "Phosphatidylcholine (O-37:6)",
        "Phosphatidylcholine (O-37:7)",
        "Phosphatidylcholine (O-38:3)",
        "Phosphatidylcholine (O-38:6)",
        "Phosphatidylcholine (O-38:7)",
        "Phosphatidylcholine (O-40:6)",
        "Phosphatidylcholine (O-40:7)",
        "Sphingomyelin (d33:1);Sphingomyelin (DH33:1)",
        "Sphingomyelin (d34:1);Sphingomyelin (DH34:1)",
        "Sphingomyelin (d34:2);Sphingomyelin (DH34:2)",
        "Sphingomyelin (d36:1);Sphingomyelin (DH36:1)",
        "Sphingomyelin (d36:2);Sphingomyelin (DH36:2)",
        "Sphingomyelin (d40:1);Sphingomyelin (DH40:1)",
        "Sphingomyelin (d40:2);Sphingomyelin (DH40:2)",
        "Sphingomyelin (d41:2);Sphingomyelin (DH41:2)",
        "Sphingomyelin (d42:1);Sphingomyelin (DH42:1)",
        "Sphingomyelin (d42:2);Sphingomyelin (DH42:2)",
        "Sphingomyelin (d42:3);Sphingomyelin (DH42:3)",
    ),
    "cral-trio__0.80": (
        "Lysophosphatidylcholine (34:5);Phosphatidylcholine (O-34:5)",
        "Lysophosphatidylcholine (36:4);Phosphatidylcholine (O-36:4)",
        "Lysophosphatidylcholine (38:5); Phosphatidylcholine (O-38:5)",
        "Phosphatidylcholine (30:0)",
        "Phosphatidylcholine (30:1)",
        "Phosphatidylcholine (30:2)",
        "Phosphatidylcholine (31:0)",
        "Phosphatidylcholine (31:1)",
        "Phosphatidylcholine (32:0)",
        "Phosphatidylcholine (32:1)",
        "Phosphatidylcholine (32:2)",
        "Phosphatidylcholine (33:1)",
        "Phosphatidylcholine (33:2)",
        "Phosphatidylcholine (34:0)",
        "Phosphatidylcholine (34:1)",
        "Phosphatidylcholine (34:2)",
        "Phosphatidylcholine (34:3)",
        "Phosphatidylcholine (34:4)",
        "Phosphatidylcholine (35:1)",
        "Phosphatidylcholine (35:2)",
        "Phosphatidylcholine (35:4)",
        "Phosphatidylcholine (36:1)",
        "Phosphatidylcholine (36:2)",
        "Phosphatidylcholine (36:3)",
        "Phosphatidylcholine (36:4)",
        "Phosphatidylcholine (36:5)",
        "Phosphatidylcholine (36:6)",
        "Phosphatidylcholine (37:4)",
        "Phosphatidylcholine (37:5)",
        "Phosphatidylcholine (38:2)",
        "Phosphatidylcholine (38:3)",
        "Phosphatidylcholine (38:4)",
        "Phosphatidylcholine (38:5)",
        "Phosphatidylcholine (38:6)",
        "Phosphatidylcholine (38:7)",
        "Phosphatidylcholine (39:4)",
        "Phosphatidylcholine (39:5)",
        "Phosphatidylcholine (39:6)",
        "Phosphatidylcholine (40:2)",
        "Phosphatidylcholine (40:4)",
        "Phosphatidylcholine (40:5)",
        "Phosphatidylcholine (40:6)",
        "Phosphatidylcholine (40:7)",
        "Phosphatidylcholine (40:8)",
        "Phosphatidylcholine (42:10)",
        "Phosphatidylcholine (42:8)",
        "Phosphatidylcholine (O-32:1)",
        "Phosphatidylcholine (O-32:2)",
        "Phosphatidylcholine (O-32:3)",
        "Phosphatidylcholine (O-33:3)",
        "Phosphatidylcholine (O-34:1)",
        "Phosphatidylcholine (O-34:2)",
        "Phosphatidylcholine (O-34:3)",
        "Phosphatidylcholine (O-34:4);Lysophosphatidylcholine (34:4)",
        "Phosphatidylcholine (O-35:5)",
        "Phosphatidylcholine (O-36:1)",
        "Phosphatidylcholine (O-36:2)",
        "Phosphatidylcholine (O-36:3)",
        "Phosphatidylcholine (O-36:5)",
        "Phosphatidylcholine (O-36:5); Lysophosphatidylcholine (36:5)",
        "Phosphatidylcholine (O-36:6);Lysophosphatidylcholine (36:6)",
        "Phosphatidylcholine (O-37:4)",
        "Phosphatidylcholine (O-37:6)",
        "Phosphatidylcholine (O-37:7)",
        "Phosphatidylcholine (O-38:3)",
        "Phosphatidylcholine (O-38:6)",
        "Phosphatidylcholine (O-38:7)",
        "Phosphatidylcholine (O-40:6)",
        "Phosphatidylcholine (O-40:7)",
    ),
    "cral-trio__0.85": (
        "Phosphatidylethanolamine (28:1)",
        "Phosphatidylethanolamine (30:1)",
        "Phosphatidylethanolamine (30:2)",
        "Phosphatidylethanolamine (31:1)",
        "Phosphatidylethanolamine (32:1)",
        "Phosphatidylethanolamine (32:2)",
        "Phosphatidylethanolamine (33:1)",
        "Phosphatidylethanolamine (33:2)",
        "Phosphatidylethanolamine (34:1)",
        "Phosphatidylethanolamine (34:2)",
        "Phosphatidylethanolamine (34:3)",
        "Phosphatidylethanolamine (35:1)",
        "Phosphatidylethanolamine (35:2)",
        "Phosphatidylethanolamine (36:1)",
        "Phosphatidylethanolamine (36:2)",
        "Phosphatidylethanolamine (36:3)",
        "Phosphatidylethanolamine (37:2)",
        "Phosphatidylethanolamine (38:2)",
        "Phosphatidylethanolamine (38:4)",
        "Phosphatidylethanolamine (O-38:6)",
        "Phosphatidylethanolamine (O-40:8)",
    ),
}

# What each block measures on the table it was chosen on:
# key -> (isolation, positives, rows, species, proteins)
BLOCK_GEOMETRY = {
    "0.40": (0.458, 66, 2275, 65, 35),
    "0.50": (0.499, 73, 2345, 67, 35),
    "0.546": (0.546, 102, 2975, 85, 35),
    "0.55": (0.550, 41, 1435, 41, 35),
    "0.554": (0.554, 51, 525, 15, 35),
    "0.596": (0.596, 52, 560, 16, 35),
    "0.60": (0.600, 43, 1470, 42, 35),
    "0.600": (0.600, 106, 3010, 86, 35),
    "0.70": (0.700, 103, 1645, 47, 35),
    "0.80": (0.800, 78, 2240, 64, 35),
    "0.85": (0.850, 74, 735, 21, 35),
    "0.90": (0.900, 77, 1820, 52, 35),
    "0.95": (0.950, 67, 1155, 33, 35),
    "cral-trio__0.56": (0.555, 15, 801, 89, 9),
    "cral-trio__0.65": (0.650, 21, 1197, 133, 9),
    "cral-trio__0.70": (0.700, 21, 810, 90, 9),
    "cral-trio__0.80": (0.800, 18, 621, 69, 9),
    "cral-trio__0.85": (0.850, 34, 189, 21, 9),
}

# This call's own chosen keys against the whole table: 9905 rows, 634 positives.
